### ISSUE TITLE
Questions about the sparse lasso soluction from the implemented ADMM

### ISSUE THREAD

**Issue by vtshen** [yixuan/ADMM#11]
I have a question about the estimated sparse LASSO coefficients. Based on Dr. Boyd MATLAB [code in standford](https://web.stanford.edu/~boyd/papers/admm/lasso/lasso.html) the estimated coefficients are small, but not zero.

The readme file shows that the implemented ADMM method has sparse-patten estimated coefficients, similar to that from the glmnet. I was curious how could you achieve that? I am not familiar with cpp so am not able to find the trick.

Thanks

**Comment by yixuan** [comment]
I guess it depends on whether you pick the X variable or the Z variable as the solution. X is dense and Z is sparse, but at the limit they are equal due to the constraint.

**Comment by vtshen** [comment]
Thanks so much for the help. I double check the MATLAB code, variable X is dense but variable Z is sparse.
