### ISSUE TITLE
Demo bug from http://statr.me/admm/

### ISSUE THREAD

**Issue by harryprince** [yixuan/ADMM#3]
When I run this command, I find a bug.

```
fit3 = mod3$fit()
Error in .Call("admm_dantzig", .self$x, .self$y, .self$lambda, .self$nlambda,  : 
  "admm_dantzig" not available for .Call() for package "ADMM"
```

**Comment by yixuan** [comment]
Yeah. This is because the Dantzig selection has been removed in the current version, since it is very hard to converge using ADMM. It may require better algorithm to solve.
