### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by abeylinNEG** [yixuan/ADMM#5]
Dear Sir,

I have problem with ADMM installation. I am using latest R-3.3.0 .
This is what I have finally using the install_github("yixuan/ADMM") command
ParLasso.o:ParLasso.cpp:(.text$_ZN17PADMMLasso_Master4initEdd[__ZN17PADMMLasso_Master4initEdd]+0x12b): undefined reference to `ssyrk_'
ParLasso.o:ParLasso.cpp:(.text$_ZN17PADMMLasso_Master4initEdd[__ZN17PADMMLasso_Master4initEdd]+0x38e): undefined reference to `ssyrk_'
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'ADMM'
- removing 'C:/Users/Alex Beylin/Documents/R/win-library/3.3/ADMM'
  Error: Command failed (1)

I am very interesting in your package.
Please advise.

Regards

Alex Beylin

**Comment by yixuan** [comment]
Thanks for the report. This issue has been fixed in the recent commits.

**Comment by abeylinNEG** [comment]
Thanks Yixuan,

It works.

Regards,

Alex
