### ISSUE TITLE
Adding interfaces for platforms other than R

### ISSUE THREAD

**Issue by Red-Portal** [yixuan/ADMM#6]
Hi,
I would like to develop additional interfaces for your library.
I'm not experienced in R packages so can you give me some directions?

Where should I look first in order to develop interfaces.

**Comment by yixuan** [comment]
This package is mostly for experiment purpose and I guess for specific tasks it's more straightforward to implement the algorithm from scratch. However, the core part of this package was written in C++ with the Eigen library, so feel free to use the code inside the `src` directory if it helps.

**Comment by yixuan** [comment]
There was another experimental package I wrote for Spark: https://github.com/yixuan/ADMM-Spark. Don't take it too seriously. It was written long time ago based on an old version of Spark. But it may provide some insights for your own project.

**Comment by Red-Portal** [comment]
Thanks I'll look into it
